dropTimeMs: 180
sourceId: 15005
slot: 1

allowedGroups:
  - 2001

fne:
  name: WL Patch
  peerId: 9000123
  address: 127.0.0.1
  port: 62031
  passphrase: "RPT1234"
  encrypted: false
  presharedKey: "000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F"

whackerLink:
  name: "WL Patch"
  address: 127.0.0.1
  port: 3000
  site:
    name: "Central Site"
    controlChannel: "772.74375"
    voiceChannels: []
    location:
      x: 757.89
      y: 1274.17
      z: 360.3
    systemID: 1
    siteID: 1
    range: 1.5