# General Configuration
system:
  mode: 1 # (Dont change not used rn)
  dstId: "2001" # TGID that will be passed for bridging
  site:
    name: "Central Site"
    controlChannel: "772.74375"
    voiceChannels: []
    location:
      x: 757.89
      y: 1274.17
      z: 360.3
    systemID: 1
    siteID: 1
    range: 1.5

# DVM Bridge Configuration
dvmBridge:
  name: "CN BRIDGE" # Textual Alias
  address: 127.0.0.1 # Address to send UDP to
  txPort: 32001 # Port to send UDP to
  rxPort: 34001 # Port to bind to

# WhackerLink Master Configuration
master:
  name: "CN BRIDGE" # Textual Alias
  address: 127.0.0.1 # Address to connect to
  port: 3000 # Port to connect to